//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("OctoTool")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Complete Innovations Inc.")]
[assembly: AssemblyProduct("OctoTool")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0.6")]
[assembly: AssemblyInformationalVersion("1.0.0.6")]
[assembly: AssemblyCopyright("Copyright © 2000-2017 Complete Innovations Inc.")]
[assembly: AssemblyTrademark("")]
[assembly: Guid("268C840F-9A02-4135-B8A6-F813BC03CB5D")]
[assembly: ComVisible(false)]

